steps:

- id: "Execução dos testes unitários"
  name: 'golang'
  args: ['go', 'test', './src']

- id: "Build da imagem Docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dfdx/somago', '.']

- id: "Push da imagem Docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dfdx/somago']
